= {connection} connection reference
:last_updated: 03/5/2024
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:description: Learn about the fields used to create a Mode connection using ThoughtSpot Connections.
:connection: Mode
:jira: SCAL-176923

You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.

Connection name:: Enter a new {connection} connection name.
Connection description:: Provide a short description of the connection._(Optional)_
Host:: Enter the host name associated with the database.
Port:: Enter the port number associated with the database.
User:: Enter the user associated with the {connection} database.
Password:: Enter the password associated with the user of the {connection} database.


'''
> **Related information**
>
> * xref:connections-mode-add.adoc[Add a connection]
> * xref:connections-mode-edit.adoc[Edit a connection]
> * xref:connections-mode-remap.adoc[Remap a {connection} connection]
> * xref:connections-mode-delete-table.adoc[Delete a table from a {connection} connection]
> * xref:connections-mode-delete-table-dependencies.adoc[Delete a table with dependent objects]
> * xref:connections-mode-delete.adoc[Delete a {connection} connection]
> * xref:connections-mode-passthrough.adoc[]