= ThoughtSpot editions and shared tenants
:last_updated: 4/24/2024
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:writer: Mary
:page-toclevels: -1
:description: This article provides information about the features supported on a shared tenant and in ThoughtSpot editions.
:jira: SCAL-SCAL-214091

This article provides information about ThoughtSpot capabilities that are supported in ThoughtSpot editions and on a shared tenants.

|===
Capability|Enterprise edition|Shared tenant

|Authentication: SAML SSO with IAMv2|Yes|Yes (only with IAM v2)|

VPN, Privatelink|Yes|No (Bridge connectivity GA 10.1.0.cl)|

Roles Based Access Control (RBAC)|Yes (early access)|Yes (default)|

Style & Chart Customization|Yes|Yes|

System Activities/Liveboards|Yes|Yes

a|Application Settings Admin panel:

* Search

* SpotIQ

* CSV Upload

* Early access features
|Yes|No

|Org-Aware Flags and customizations|Yes|No

|Security Settings (Develop tab)
|Yes|Yes

|Custom URL Support|Yes|No|
|===

== Limitations
Only cluster-level flag application is supported for multi-tenant clusters. These flags are applicable to all ThoughtSpot editions customers hosted on the multi-tenant cluster. Flags are applied only during a maintenance window.

Early Access/Beta features are not supported for ThoughtSpot editions customers.

Custom URLs are not supported for Pro edition customers. Only the URLs listed below are supported for customer clusters:

* TS Cloud URL for TSA Pro:
** <customername>.prod01-<na/eu/ap>.thoughtspot.cloud
* TS Cloud URL for TSE Pro:
** <customername>.tseprod01-<na/eu/ap>.thoughtspot.cloud

Customer specific allowlisting is not supported for ThoughtSpot editions customers.

COMs is not enabled for ThoughtSpot editions customers.



