= Administrator capabilities in each ThoughtSpot edition
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:page-toclevels: -1
:description: This article provides information about the capabilities administrators have in each ThoughtSpot edition.

This article provides information about the capabilities administrators have in each ThoughtSpot edition.

== Administrator capabilities by edition

[cols="30%,10%,10%,10%,10%,10%,10%,10%"]
|===
|*Administrator capability* ^.^|Free Trial ^.^|Team Edition ^.^|Essentials ^.^|TSA Pro Edition ^.^|TSE Pro Edition ^.^|TSA Enterprise ^.^|TSE Enterprise

|Org creation and management
^.^|
^.^|
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]

|User management
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]

|Groups and roles management
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]

|SAML user authentication
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]

|System monitoring (system Liveboards)
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]

|ThoughtSpot Sage preview
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]

|SpotIQ privileges
^.^|image:checkmark_black.svg[Yes]
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]

|Developer privileges
^.^|image:checkmark_black.svg[Yes]
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes]
^.^|
^.^|image:checkmark_black.svg[Yes]

|Data management privileges
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
^.^|image:checkmark_black.svg[Yes]
|===

