= Administration of ThoughtSpot editions
:last_updated: 11/05/2021
:linkattrs:
:experimental:
:page-layout: default-cloud
:page-aliases:
:page-toclevels: -1
:description: This article provides information about the capabilities administrators have in each ThoughtSpot edition.
:jira: SCAL-179604

This article provides information about the capabilities administrators have in each ThoughtSpot edition. For details on the specific features of the Team, Essentials, Pro, and Enterprise editions, see the https://www.thoughtspot.com/pricing[pricing page^] on ThoughtSpot.com.

== Administrator capabilities by edition

[cols="30%,10%,10%,10%,10%,10%,10%,10%" stripes="even"]
|===
.^|Capability ^.^|{set:cellbgcolor:#FFFFF}Free Trial ^.^|Team Edition ^.^|Essentials Edition ^.^|TSA Pro Edition ^.^|TSE Pro Edition  ^.^|TSA Enterprise Edition ^.^|TSE Enterprise Edition

|*User management*
^.^|{set:cellbgcolor:#FFFFF}image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|*Data management privileges*
^.^|{set:cellbgcolor:#FFFFF}image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|*System monitoring (system Liveboards)*
^.^|{set:cellbgcolor:#FFFFF}image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|*ThoughtSpot Sage preview*
^.^|{set:cellbgcolor:#FFFFF}image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|*SpotIQ privileges*
^.^|{set:cellbgcolor:#FFFFF}image:checkmark_black.svg[Yes,15]
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|*Groups and roles management*
^.^|{set:cellbgcolor:#FFFFF}
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|*SAML user authentication*
^.^|{set:cellbgcolor:#FFFFF}
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]

|*Developer privileges*
^.^|image:checkmark_black.svg[Yes,15]
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|
^.^|image:checkmark_black.svg[Yes,15]

|*Org creation and management*
^.^|{set:cellbgcolor:#FFFFF}
^.^|
^.^|
^.^|
^.^|
^.^|image:checkmark_black.svg[Yes,15]
^.^|image:checkmark_black.svg[Yes,15]
|===



