= Known issues
:keywords: known issues
:last_updated: 2/15/2024
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:linkattrs:
:jira: SCAL-197719

These are the known issues in this release of ThoughtSpot Cloud.

[#releases-9-11-x]
== 9.11.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-184583
|TBD
a|*Symptoms*:

Fail to generate query

*Conditions*:

 This change was introduced in 9.4. This only impacts in certain edge case and that too for software → cloud migration.
2. columns under the aggregate expression span multiple non-shared dimensions

TBD.

*Workaround*:

Modify the query to add a no-op

|SCAL-169186
|TBD
a|*Symptoms*:

User is expecting to happen is that the filter = 8 is applied to the CTE query_0.

This does not seem to be the case.

*Conditions*:

The following is testing conducted with the new group reaggregation logic.

tscli service --adv add-javaopt tomcat.tomcat D orion.dataGenRules.enableGroupAggregateNewReaggregation true

Assuming I have a formula defined as the following:

groupFX = group_aggregate ( sum ( Quantity ) , { Line Number , OrderKey } , query_filters ( ) )

then I have a search such as: [quantiy] [orderkey] groupFX = 8

TBD.

*Workaround*:

disable 'tscli service --adv add-javaopt tomcat.tomcat D orion.dataGenRules.enableGroupAggregateNewReaggregation false'
|===