= Known issues
:keywords: known issues
:last_updated: 7/18/2024
:author: Mark Plummer
:experimental:
:page-layout: default-cloud
:page-toclevels: -1
:linkattrs:
:jira: SCAL-206809 (9.12.0.cl), SCAL-210330 (9.12.5.cl), SCAL-214503 (10.0.0.cl),

These are the known issues in this release of ThoughtSpot Cloud.
////
[#releases-10-0-x]
== 10.1.0.cl known issues

[cols="17%,39%,38%"]
|===
|Issue ID |Description|Symptoms, conditions, and workaround

|SCAL-213767
|Error encountered during analysis" due to "DB queries
a|*Symptoms*:
SpotIQ Analyze request fails due to failure in DbQuery calls.


*Conditions*:
Using a hard-coded value as the timeout while making DbQueries from SpotIQ causes DbQuery to fail when there are many SpotIQ Analyze requests.

*Workaround*:
None.

|SCAL-211518
|Liveboards cannot be migrated from one Org to another Org.
a|*Symptoms*:
Users _without_ permission to access the datasource were able to upload TML using the `tspublicAPI` but were prevented from doing so through the UI.


*Conditions*:


*Workaround*:

|SCAL-196442
|Sorting issues with measure inside a pivot table [Charts item]
a|*Symptoms*:
Sorting a field which contains measure only updates rows

*Conditions*:
Sorting a pivot table using search bar, or by updating sorting by a measure.

*Workaround*:
Sort the respective pivot table by rows or columns using the corresponding header.
|===
////