= Personalized Liveboards
:last_updated: 10/17/2023
:linkattrs:
:experimental:
:page-layout: default-cloud-early-access
:page-aliases: /complex-search/pinboard-filters.adoc
:description: You can personalize Liveboards by applying filters that are persisted.

Liveboards that contain consolidated data for all business users can now be personalized for a specific user or group. You can filter values to display only the information that is relevant to you, and save the personalized Liveboard. The personalized Liveboard retains the filter values, remains synced with the original Liveboard, and inherits relevant changes from the original. This allows you to bookmark a personalized Liveboard for easy access to the information you need, and eliminates the need to create a personal copy of a Liveboard which can result in the copy falling out of sync with the original.

Users who don't have access to the underlying data source can view a Liveboard but can't interact with it by applying filters. Only users with access to the underlying data source can create and save personalized Liveboards. New filters can't be added in a personalized Liveboard, they must be added in the original.

NOTE: If the original Liveboard is deleted, all personalized versions of it are deleted as well.


