= Spotter
:last_updated: 11/19/24
:author: Naomi
:linkattrs:
:experimental:
:page-layout: default-cloud
:description:
:jira: SCAL-228500

Introducing Spotter, our new AI-powered, unified conversational search experience. This feature replaces the previous Sage search experience. When enabled, you can enter the Spotter interface from the Spotter module on the Home page, or by clicking *Spotter* on any visualization pinned to a Liveboard.


+++
<video autoplay loop muted controls width="800" controlsList="nodownload">
<source src="https://docs.thoughtspot.com/cloud/10.3.0.cl/_images/spotter.mp4" type="video/mp4">
</video>
+++


You can ask successive questions to hone in on business insights, open a preview of the underlying data, drill down, edit or undo changes to the resulting AI-generated Answers, see what terms Spotter changed from answer to answer, and submit feedback on the answers received. Analysts can also coach Spotter to guide Spotter's interpretations from the Data Workspace. To enable Spotter, contact your administrator.


Access Spotter from the Home page *Ask a business question in natural language* module, or by hovering over a visualization in a Liveboard and clicking *Spotter*.


[NOTE]
====
Spotter for Liveboards will not be enabled on the following:

* Visualizations created using data sources or Worksheets which are not AI-enabled.
* Visualizations using multiple data sources.
* Visualizations of the note tile or headline chart type.
====


