= Query and analyze data
:author: Naomi
:last_updated: 7/25/24
:experimental:
:page-layout: default-cloud
:linkattrs:
:description: Query and analyze data.
:product: Analyst Studio

Learn how to query data, use AI assistance to generate SQL, create reusable Datasets, add Parameters to Reports, and develop and reuse saved `SELECT` statements.

** xref:studio-querying-data.adoc[Querying data] +
How to query data in {product}.
** xref:studio-ai-assist.adoc[AI Assist] +
Generate SQL using AI assistance.
** xref:studio-datasets.adoc[Datasets] +
Curate tables of data that can be reused across multiple Reports.
** xref:studio-notebook.adoc[The Notebook] +
Get started with the Python and R Notebook.
** xref:studio-parameters.adoc[Parameters] +
How to add Parameters to {product} Reports using Liquid.
** xref:studio-viz-filters.adoc[Visualization filters] +
How to add filters to a visual in the Chart Builder.
** xref:studio-definitions.adoc[Definitions] +
Develop and reuse saved `SELECT` statements.
