= Analyst Studio
:author: Naomi
:last_updated: 10/1/24
:experimental:
:page-layout: default-cloud
:linkattrs:
:description: Get started.
:product: Analyst Studio

Use Analyst Studio to connect to your team's most important SQL databases, build Reports that bring together your data team and business users for fast, quality decisions, customize your analysis for sharing and presentation, and scale your analytics to match the growth of your business. Once you have connected your data to Analyst Studio and invited your first set of new users, you can instantly begin performing analysis and sharing insights across your organization.

Learn more here:

////
** xref:studio-quick-reference-guide.adoc[Quick reference guide] +
First steps with {product}.
////
** xref:studio-getting-started-with-analyst-studio.adoc[Getting started with Analyst Studio] +
A guide on getting started with {product}.
** xref:studio-open-source-code-attributions.adoc[Open Source Code Attributions] +
A list of Open Source Code Attributions that {product} supports.
** xref:studio-supported-browsers.adoc[Supported browsers] +
A list of the browsers that {product} supports.

////
** xref:studio-release-notes.adoc[Release notes] +
Stay up to date with the latest updates.
////