= 9.8.0.sw Release Notes
:experimental:
:last_updated: 10/26/23
:linkattrs:
:page-aliases: /release/notes.adoc
:description: These release notes include information about new and enhanced features.

++++
<style>
.badge-update-whats-new-beta {
  font-style: normal !important;
  top: -0.03rem !important;
}

</style>
++++

ThoughtSpot version 9.8.0.sw is now available.

These release notes include information about new and enhanced features.

To see our feature deprecation plans, please see xref:deprecation.adoc[].

For a complete list of issues that we fixed in this release, see xref:fixed.adoc#releases-9-5-x[Fixed issues].

* <<new-9-8-0,9.8.0.sw New Features and Functionality>>
* <<upgrade-paths,Supported Upgrade Paths>>

[#new-9-8-0]
== 9.8.0.sw New Features and Functionality


* <<analyst-9-8-0-sw,For the Analyst>>
* <<business-user-9-8-0-sw,For the Business User>>
* <<data-engineer-9-8-0-sw,For the Data Engineer>>
* <<it-ops-engineer-9-8-0-sw,For the IT Ops Engineer>>
* <<developer-9-8-0-sw,For the Developer>>

[#analyst-9-8-0-sw]
=== For the Analyst

[#business-user-9-8-0-sw]
=== For the Business User

// Naomi -- scal-161857, SCAL-160779
Verified Liveboards::
We made the following enhancements to verified Liveboards:

- When you request verification, you can now see the underlying data sources that will be shared with the verifier.
- The name of the Liveboard now appears in verification request emails.
- When editing an Answer on or pinning an Answer to a verified Liveboard, a warning banner appears indicating it may need to be verified again.

[#data-engineer-9-8-0-sw]
=== For the Data Engineer

[#it-ops-engineer-9-8-0-sw]
=== For the IT Ops Engineer

// scal-159716
tscli command updates::
We have updated the tscli command syntax to retrieve history. For more information, see xref:tscli-command-ref.adoc#tscli-update[tscli get history].

Parameter runtime overrides::
Adjust Parameter values at runtime from Liveboard or Answer URLs, or using REST API v1 requests. For more information, see
xref:parameters-use.adoc#runtime-overrides[Runtime overrides for Parameters]
and
link:https://developers.thoughtspot.com/docs/?pageid=runtime-params[Runtime Parameters,window=_blank].


[#developer-9-8-0-sw]
=== For the Developer

Customers licensed to embed ThoughtSpot can use ThoughtSpot Everywhere features and Visual Embed SDK.

To enable ThoughtSpot Everywhere on your cluster, contact {support-url}.

For information about ThoughtSpot Everywhere, refer to  link:https://developers.thoughtspot.com/docs[ThoughtSpot Everywhere Documentation, window=_blank].

[#upgrade-paths]
== Supported Upgrade Paths

If you are running one of the following versions, you can upgrade to the 9.8.0.sw release directly:

* 9.5.0.sw to 9.8.0.sw
* 9.0.1.sw to 9.8.0.sw

This includes any hotfixes or customer patches on these branches.

If you are running a different version, you must do a multiple pass upgrade.

First, upgrade to version 9.5.0.sw or 9.0.1.x, and then to the 9.8.0.sw release.

NOTE: To successfully upgrade your ThoughtSpot cluster, all user profiles must include a valid email address. Without valid email addresses, the upgrade is blocked.
