= Runtime filters
:last_updated: 05/10/2022
:linkattrs:
:page-partial:
:experimental:
:description: With runtime filters, you can filter an answer or Liveboard through URL query parameters.


With runtime filters, you can filter an answer or Liveboard through URL query parameters. Use this approach with the Data API, and with embedded answers and Liveboards.

Use runtime filters to filter data at the time of retrieval; see xref:data-api.adoc[Data REST API].

.Pinboard runtime filter

In this example, the Liveboard URL uses the runtime filter on the column `Color`, and returns values that are equal (EQ) to "red".

[source,text]
----
http://<thoughtspot_server>:<port>/?col1=Color&op1=EQ&val1=red#
/pinboard/e36ee65e-64be-436b-a29a-22d8998c4fae
----

.REST API runtime filter

In this example, the URL for a xref:data-api.adoc[Data REST API] call uses a runtime filter on the column `Category`, and returns values that are equal to `mfgr%2324`.

[source,text]
----
http://<thoughtspot_server>:<port>/callosum/v1/tspublic/v1/pinboarddata?
id=e36ee65e-64be-436b-a29a-22d8998c4fae&col1=Category
&op1=EQ&val1=mfgr%2324
----

ThoughtSpot attempts to find a matching column in the Liveboard or visualization using the `col` field as `name`.
You can add any number of filter sets by adding additional parameters for columns, operations, and values to the URL. For operators that support more than one value, pass `val1=foo&val1=bar`, and so on.

If the Liveboard or answer already has one or more filters, ThoughtSpot combines runtime filter(s) in an `AND` condition.
This means that the returned data must meet the conditions of all filters, those supplied in the runtime filter, and those included in the Liveboard or visualization itself.

== Supported data types

You can use runtime filters on these data types: xref:data-types.adoc#varchar[`VARCHAR`], xref:data-types.adoc#bigint[`BIGINT`], xref:data-types.adoc#int[`INT`], xref:data-types.adoc#float[`FLOAT`], xref:data-types.adoc#double[`DOUBLE`], xref:data-types.adoc#bool[`BOOLEAN`], xref:data-types.adoc#date[`DATE`], xref:data-types.adoc#datetime[`DATETIME`], and
xref:data-types.adoc#time[`TIME`].

NOTE: You must specify the date in epoch time (also known as POSIX or Unix time) for `DATE` and `DATETIME` values.

== Best practices

You can use runtime filters with the Data REST API to create dynamic controls in your application.
For example, you could use the Data REST API to get a list of possible filters for a visualization.
Then use that data to populate a _select_ list in your web application.
When a user selects an option, the application passes that option as a runtime filter. The resulting answer or Liveboard satisfies the conditions of the filter.

[#limitations-of-runtime-filters]
== Limitations of runtime filters

* The `DATE` and `DATE_TIME` data types must be specified as EPOCH time (Unix or POSIX time) in runtime filters.

* Runtime filters work only on Answers and Liveboard visualizations built from Worksheets. Runtime filters on visualizations and Answers built directly from Tables, Views, and SQL Views do not work because the possibility of multiple join paths and join path choice is not supported as input in runtime filters.

* Runtime filters do not allow you to apply `HAVING` filters in the URL parameters.



'''
> **Related information**
>
> * xref:runtime-filter-apply.adoc[]
> * xref:runtime-filter-operators.adoc[]
