The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-5-0-cl-first,For the First User>>
* <<10-5-0-cl-analyst,For the Analyst>>
* <<10-5-0-cl-business-user,For the Business User>>
* <<10-5-0-cl-data-engineer,For the Data Engineer>>
* <<10-5-0-cl-developer,For the Developer>>

[#10-5-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-5-0-cl-analyst]
=== For the Analyst


[#10-5-0-cl-business-user]
=== For the Business User

// Naomi. jira: SCAL-224933. docs jira: SCAL-228737
Custom comparison point for KPI charts [.badge.badge-early-access-relnotes]#Early Access#::
Previously, time-series KPI charts had limited options when comparing to past periods. A weekly KPI could be compared against the previous week, the previous month's same week, the previous quarter's same week, or the previous year's same week. Now, you can set a custom point in data against which ThoughtSpot compares the most recent data point, any number of weeks ago. Your chosen comparison point persists for all viewers of the Liveboard. To enable this feature, contact your administrator.

// Naomi – jira: SCAL-220304. docs jira: SCAL-?
Compact Liveboard header::
We have streamlined the design of Liveboard headers to ensure maximum visibility of Liveboard visualizations no matter the size of the screen.
+
For more information, see
xref:liveboard.adoc#compact-header[Liveboards].

[#10-5-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-208829. docs jira: SCAL-230240.
Databricks service principal with OAuth:: You can now authenticate a Databricks connection using a service principal and OAuth secret.

// Naomi. jira: SCAL-227647, SCAL-227649. docs jira: SCAL-?
OAuth Connections sign-in for Search Data and Answer view:: Admin users now have more control on how users sign in to Connections authenticated using OAuth when the connection authentication has expired. Previously, the *Sign in with OAuth* button appeared only on Liveboards built on the Connection. Now, users can access the sign-in flow from Search Data and Answers as well.

// Naomi. jira: SCAL-224193. docs jira: SCAL-224199
Join cardinality change for global joins [.badge.badge-early-access-relnotes]#Early Access#::
You can now change the cardinality of a join (1:1, 1:Many, Many:1) without needing to delete and remake the join. To enable this feature, contact your administrator.

[#10-5-0-cl-it-ops]
=== For the IT/Ops Engineer


[#10-5-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
