The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-4-0-cl-first,For the First User>>
* <<10-4-0-cl-analyst,For the Analyst>>
* <<10-4-0-cl-business-user,For the Business User>>
* <<10-4-0-cl-data-engineer,For the Data Engineer>>
* <<10-4-0-cl-developer,For the Developer>>

[#10-4-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-4-0-cl-analyst]
=== For the Analyst

// Naomi. JIRA: SCAL-171986. docs jira: SCAL-225582
Configuring color gradients [.badge.badge-early-access-relnotes]#Early Access#::
You can now choose multiple colors to define a gradient in charts that support gradients -- geo heatmap, geo area, heatmap, and treemap charts. You can control the low, mid, and high values, and numerical value points to customize the gradient. For more information, see
xref:chart-color-change.adoc[Change chart colors].


[#10-4-0-cl-business-user]
=== For the Business User

// Naomi. jira: SCAL-223692, SCAL-222817. docs jira: SCAL-228500
Spotter for Cloud [.badge.badge-early-access-relnotes]#Early Access#::
Introducing Spotter, our new AI-powered, unified conversational search experience. This feature replaces the previous Sage search experience. When enabled, you can enter the Spotter interface from the search bar on the Home page, or by clicking *Spotter* on any visualization pinned to a Liveboard.
+
You can ask successive questions to hone in on business insights, open a preview of the underlying data, drill down, edit or undo changes to the resulting AI-generated Answers, see what terms Spotter changed from question to question, and submit feedback to train Spotter's interpretations. Analysts can also coach Spotter on how to interpret certain terms from the Admin page. To enable this feature, contact your administrator.
+
For more information, see
xref:spotter.adoc[Spotter for Cloud].

// Naomi. jira: SCAL-222476. docs jira: SCAL-225755
Chart visualization enhancements::
We made the following changes to visualizations on Liveboards:
+
--
* You can now hover over items in a visualization's legend to highlight the data that corresponds to that column.
* You can hover over a truncated legend to see the corresponding column name in a tooltip.
* We improved the readability for the smallest size of Liveboard visualizations. Now, minimum-sized visualizations display only the chart, omitting the x- and y-axes and labels. You can hover over select data points to see the values.
--
+
For more information, see
ifndef::pendo-links[]
xref:liveboard.adoc[Basic Liveboard usage].

// Naomi. docs jira: SCAL-229731
Liveboard breakpoints:: We have updated the Liveboard breakpoints. Windows narrower than 639 pixels now display one column of visualizations. Windows wider than 639 pixels but narrower than 1033 pixels display two columns of visualizations.

// Naomi. jira: SCAL-212737. docs jira: SCAL-226578
Compact Liveboard header [.badge.badge-early-access-relnotes]#Early Access#:: We have streamlined the design of Liveboard headers to ensure maximum visibility of Liveboard visualizations no matter the size of the screen. To enable this feature, contact your administrator.

[#10-4-0-cl-data-engineer]
=== For the Data Engineer

// Naomi. jira: SCAL-210169. docs jira: SCAL-229394
Control default and available chart types [.badge.badge-beta-relnotes]#Beta#::
You can now control the default display mode for Answers (table or chart). You can also decide which chart types are available and default for your cluster. For example, you can set the default chart type for an Answer as a bar chart. You could also decide to remove pie charts from your cluster. To enable this feature, contact {support-url}. For more information, see
xref:charts.adoc#control-default[Control default and available chart types].

// Naomi. jira: SCAL-189319. docs jira: SCAL-228671
ThoughtSpot Status [.badge.badge-beta-relnotes]#Beta#::
Admin users can now navigate to the ThoughtSpot Status page to monitor the health of services on their cluster. We have updated the user interface to make it more user-friendly. The Status page displays the status of different ThoughtSpot services, like Authentication, Data Connections, Infrastructure Services, KPI Monitor, Search Data, Search Service, SpotIQ, Sync, and Spotter. The page also shares scheduled maintenance timelines, outage notifications, and incident reporting and updates.
+
To access the status page, add `/\#/status` to the end of your cluster url (for example, `https://<clustername>.thoughtspot.cloud/#/status`). To enable this feature, contact {support-url}. For more information, see
xref:status.adoc[Status page].

// Naomi. jira: SCAL-202688. docs jira: SCAL-213195.
Version control permissions::
We made the following changes to permissions regarding version control:
+
--
* Admin users can now assign the *Can set up version control* privilege to allow non-admin users to access the version control settings under *Admin > Application settings*, and to use Version Control REST v2 APIs.

* We renamed the previous *Can manage version control* permission to *Can toggle version control for objects*. Users with this permission and edit access to a ThoughtSpot object can enable or disable version history for that object.
--
+
For more information, see
ifndef::pendo-links[]
xref:git-version-control.adoc[Version control for Liveboards and Answers].

// Naomi. jira: SCAL-224017, SCAL-210554. docs jira: SCAL-210659
Data panel column groups::
Analysts can now set definitions in a Worksheet or Model's TML file to group columns together in the Data panel for Search Data. You can also use TML properties to enable or disable alphabetical sorting of the groups. For more information, see
xref:tml-models.adoc[TML for Models] and xref:tml-worksheets.adoc[TML for Worksheets].

// Naomi. jira: SCAL-197812. docs jira: SCAL-224478
Download custom calendar::
In the *Create a custom calendar* interface, you can now set up a template calendar and download it as a CSV file with all columns, based on the values you inputted. You can then modify the file and share it with your ThoughtSpot administrator to upload it to your database. Once the CSV is uploaded to the database, you can set up the calendar by directly mapping the table. For more information, see
xref:connections-cust-cal-create.adoc[Create a custom calendar].


[#10-4-0-cl-it-ops]
=== For the IT/Ops Engineer

[#10-4-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
