The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<10-3-0-cl-first,For the First User>>
* <<10-3-0-cl-analyst,For the Analyst>>
* <<10-3-0-cl-business-user,For the Business User>>
* <<10-3-0-cl-data-engineer,For the Data Engineer>>
* <<10-3-0-cl-developer,For the Developer>>

[#10-3-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#10-3-0-cl-analyst]
=== For the Analyst



[#10-3-0-cl-business-user]
=== For the Business User

// Naomi. jira: SCAL-210305. docs jira: SCAL-221925
Natural language search and object search:: Natural language search and object search are now separated. To search for an AI-generated answer using natural language, enter your question in the *Ask a business question in natural language* search bar on the home page. To search for related Answers and Liveboards, enter your question in the *Find existing Answers and Liveboards* search bar in the top navigation bar.



[#10-3-0-cl-data-engineer]
=== For the Data Engineer

Categorization for Connections [.badge.badge-early-access-relnotes]#Early Access#:: You can now choose to sort Connections by type rather than order added to ThoughtSpot. To enable this feature, contact your administrator.


[#10-3-0-cl-it-ops]
=== For the IT/Ops Engineer

[#10-3-0-cl-developer]
=== For the Developer

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
