The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-6-0-cl-first,For the First User>>
* <<9-6-0-cl-analyst,For the Analyst>>
* <<9-6-0-cl-business-user,For the Business User>>
* <<9-6-0-cl-data-engineer,For the Data Engineer>>
* <<9-6-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-6-0-cl-developer,For the Developer>>

[#9-6-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-6-0-cl-analyst]
=== For the Analyst

[#9-6-0-cl-business-user]
=== For the Business User

[#9-6-0-cl-slides]
ThoughtSpot for Google Slides add-on::

ThoughtSpot Connected Slides is an add-on that allows you to insert charts and live data visualizations right into your Google Slides™ presentation. Just connect to ThoughtSpot, find a chart or visualization, and add it to your slide presentation. For details, see xref:thoughtspot-slides.adoc[ThoughtSpot Connected Slides].

[#9-6-0-cl-data-engineer]
=== For the Data Engineer

[#9-6-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#9-6-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
