The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-12-0-cl-first,For the First User>>
* <<9-12-0-cl-analyst,For the Analyst>>
* <<9-12-0-cl-business-user,For the Business User>>
* <<9-12-0-cl-data-engineer,For the Data Engineer>>
* <<9-12-0-cl-developer,For the Developer>>

[#9-12-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-12-0-cl-analyst]
=== For the Analyst

// Naomi – SCAL-181312. documentation JIRA scal-201645.
Remember personalized columns in change analysis::
Personalized columns are now available to all users and on by default. Users with edit permissions on a Liveboard can set their preferred attribute columns through the change analysis window and select *Apply to all users* to keep those selections for any subsequent change analysis calculations on that Liveboard. Individual users can still override these preferences for their own calculations. +
For more information, see
xref:spotiq-change.adoc#remember-personalized[Remember personalized columns].

// Naomi – SCAL-176265. documentation JIRA scal-201646.
Drill down in change analysis [.badge.badge-early-access-relnotes]#Early Access#:: You can now drill down on specific columns in change analysis, in order to identify change drivers within your data. For example, if you run an analysis on sales monthly and find out that the 'jacket' item type changed the most, you can easily drill down on jacket sales and identify which region contributed the most to the change in sales. To enable this feature, contact your administrator. +
For more information, see
xref:spotiq-change.adoc#iterative[Iterative change analysis].

// Naomi – SCAL-180961. SCAL-130010. Documentation JIRA scal-201647. documentation JIRA scal-201649.
ThoughtSpot Sync::
We made the following enhancements to ThoughtSpot Sync:

* Using ThoughtSpot Sync, you can now sync data directly from an Answer or a custom SQL view, to Excel.
* You can now click the preview link when you create a Sync from the Data Workspace to see a preview of the resulting Answer, Liveboard, or Custom SQL view. Answer, Liveboard, and Custom SQL view previews appear in a new tab.
* When running a Sync, you can see the following information depending on the destination:

** Slack: channel name
** Microsoft Teams: team and channel
** Sheets: file name and spreadsheet name
** All others: object name and operation name

[#9-12-0-cl-business-user]
=== For the Business User

// Naomi – SCAL-188039. documentation jira SCAL-201656.
Ask Sage [.badge.badge-early-access-relnotes]#Early Access#::
You can now conversationally search ThoughtSpot using natural language on a Liveboard visualization, asking follow-up questions for further clarification or to take your analysis in a new direction. This conversational approach allows you to begin with a simple question, and ask successive questions to refine the answer you receive. ThoughtSpot translates each natural language question into a query, and answers in chart format. To enable this feature, contact your administrator.
+
For more information, see xref:ask-sage.adoc[Ask Sage].


// Naomi -- scal-177005. documentation JIRA scal-201639 (approved).
Advanced conditional formatting [.badge.badge-early-access-relnotes]#Early Access#::
In addition to using conditional formatting to visually highlight a threshold in a measure (for example, `sales > 10000`), you can now use conditional formatting to compare a column's measures to another column or to a parameter. For example, if you search for `sales this year` compared to `sales last year`, you can highlight where sales this year were less than last year. You can set multiple conditional formatting rules to a single table. To enable this feature, contact your administrator.
+
For more information, see xref:search-conditional-formatting.adoc#advanced-conditional-formatting[Advanced conditional formatting].

// Naomi -- SCAL-153878. documentation jira SCAL-201644.
Forecasting [.badge.badge-beta-relnotes]#Beta#::
You can now use SpotIQ analysis to forecast future trends for your KPIs. ThoughtSpot uses machine learning models that learn from past trends, growth, and seasonality to project how the target metric will trend in the future. To enable this feature, contact {support-url}.
+
For more information, see xref:spotiq-forecasting.adoc[Forecasting].

// Naomi – SCAL-179981. documentation jira SCAL-202909 (approved).
Sage Coach::
We made the following enhancements to Sage Coach:

* Sage Coach shows the feedback from the selected Org-ID only.
* Renamed the labels for Sage Coach under the *Data* tab as *Sage Feedback - Queries* and *Sage Feedback - Fragments*.
* Added an *Edited by* column to indicate the last person to edit specific feedback in both Fragments and Queries pages.
* Added a *Rating* column to the Fragments page to record whether the original Answer was rated accurate or inaccurate.
* Added a *Chart* preference column to the Queries page.
* Added an *Access* column to the *Sage Feedback - Fragments* page to record whether the access level is user-level or global to make it consistent with *Sage Feedback - Queries* page.

// Naomi -- SCAL-187745. documentation JIRA scal-201640
Collibra integration::
Collibra integration is now available to all users and on by default. You can now see verification status and descriptions on tables and columns imported from Collibra. This information appears when you click on the corresponding table or column in *Search data*. Once connected, this information is visible to all users. For more information, see xref:catalog-integration-collibra.adoc[Collibra catalog integration].

[#9-12-0-cl-data-engineer]
=== For the Data Engineer

// Naomi – SCAL-180544. documentation JIRA SCAL-204538 (approved)
Semi-additive measures with first and last values [.badge.badge-early-access-relnotes]#Early Access#::
A semi-additive measure, also known as snapshot data, is a measure that is usually aggregated for all attributes except for date and time. For certain measures, like inventory, you want to know what the value was at the beginning or end of a period. In that case, you can use the `last_value` function to find the inventory at the end of a month, rather than aggregating all values over the month. Similarly, you can use the `first_value` function to find out your stock at the beginning of a month. To enable this feature, contact your administrator.
+
For more information, see xref:semi-additive-measures.adoc[Semi-additive measures with `first_value` and `last_value` functions] and xref:semi-additive-modeling.adoc[Modeling data for semi-additive measures].

// Naomi -- SCAL-187745. documentation JIRA scal-201640.
Collibra catalog integration::
Collibra catalog integration is now available to all users and on by default. You can now import metadata information related to your tables and columns from Collibra into ThoughtSpot. From the Data tab, you can set up a connection to Collibra to import column descriptions, column verification status, table descriptions, and table verification status. For more information, see xref:catalog-integration-collibra.adoc[].

// Naomi – SCAL-191462, documentation jira scal-196178
Snowflake secondary role configuration for External OAuth::
ThoughtSpot now supports secondary role configuration when you create a Snowflake connection using External OAuth. When you set secondary roles to `ALL`, you can access all tables that any single role has access to and combine them in a single SQL query without having to switch roles.
+
For more information on primary and secondary roles, see link:https://docs.snowflake.com/en/user-guide/security-access-control-overview#enforcement-model-with-primary-role-and-secondary-roles[Enforcement model with primary role and secondary roles] and xref:connections-snowflake-add.adoc#secondary[Add a Snowflake connection].

// Naomi - SCAL-203459
Redshift AWS IDC OAuth:: We now support Redshift connections using AWS IDC OAuth. For more information, see
xref:connections-redshift-aws-idc-oauth.adoc[Configure AWS IDC OAuth for a Redshift connection].

// Naomi – SCAL-179763. documentation JIRA scal-201642.
User Adoption Liveboard::
You can now use the User Adoption Liveboard to understand how ThoughtSpot is saving you time with ad-hoc insights, and how many users are accessing ThoughtSpot and creating new insights every month. For more information, see
xref:user-adoption.adoc[User Adoption Liveboard] and xref:user-productivity.adoc[].

// Naomi – SCAL-148626. documentation jira SCAL-202207 (approved). SCAL-132544. documentation jira SCAL-202209 (approved)
Connection TML::
You can now use the table TML file to make changes to connection details like remapping columns and changing data type, rather than using the connection.yaml file. This allows you to make small changes to a Connection without the need to resolve all possible errors first. You can also edit or export the Connection TML file from the Data Workspace.

[#9-12-0-cl-developer]
=== For the Developer

// mark -- SCAL-194041
Develop custom charts [.badge.badge-beta-relnotes]#Beta#:: Developers can now create custom charts for ThoughtSpot using the ThoughtSpot Charts SDK. To enable this feature, contact {support-url}. For more information, see xref:chart-byoc.adoc[Custom charts].

ThoughtSpot Embedded:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
