The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-5-0-cl-first,For the First User>>
* <<9-5-0-cl-analyst,For the Analyst>>
* <<9-5-0-cl-business-user,For the Business User>>
* <<9-5-0-cl-data-engineer,For the Data Engineer>>
* <<9-5-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-5-0-cl-developer,For the Developer>>

[#9-5-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-5-0-cl-analyst]
=== For the Analyst

Improved multi-tab PDF export from Liveboards:: Previously, you couldn’t export a liveboard with more than 40 visualizations, even if they were across multiple tabs. Starting in this release, you can now export a Liveboard with more than 40 visualizations, as long a single tab has no more than 40 visualizations.

Rename filters on a Liveboard:: You can now edit the display name of filters on Liveboards to better represent your data. To try it out, click the *Edit* icon on a Liveboard, click the filter you want to rename, select *Filter options*.

Monitor alerts in ThoughtSpot notifications:: You can now see notifications for threshold and anomaly alerts in the ThoughtSpot notification service, rather than receiving emails.

Single value selection for attribute filters:: When creating a Liveboard, you can now designate attribute filters as single-select, in addition to multi-select. For example, you could choose to make a Country filter single-select, so users would only see data related to one country at a time.

Chart display enhancements:: When you create bar and column charts and slice by color, ThoughtSpot automatically enables gridlines to make the chart easier to read. You can choose to disable gridlines under the chart configuration menu. We now display lines on the axis to represent very small values and zero values.

[#9-5-0-cl-business-user]
=== For the Business User

Natural language search: "vs", "growth of", "trend":: The following keywords are now supported in natural language search: "vs", "growth of", and "trend".

Pivot table enhancements:: We made the following enhancements to pivot table charts:

- When you download an xlsx version of a pivot table, the measure values are displayed as numbers instead of the general format.
- When you download an xlsx version of a pivot table, row and column labels are shown as separate cells rather than as a column-separated list.
- You can no longer add conditional formatting to a pivot table in heatmap mode.
- Naming of subtotals and grand totals are now consistent in the chart and chart configuration dropdown.
- We now support hyperlinks in pivot tables.
- You can now choose to show or hide row and column summaries and subtotals, from the chart configuration menu. When summaries and subtotals are enabled, you can choose to display them at the top or bottom of the pivot table.

Date picker:: Date picker is now GA and on by default. We added support for rolling, fixed, and custom date filters when creating an Answer or filtering a Liveboard. Previously, when adding a date filter to a Search, ThoughtSpot supported the conditions `ON (=)`, `ON OR AFTER (>=)`, `BEFORE (<)`, and `BETWEEN`. Now, you can additionally filter for `ON OR BEFORE (\<=)`, `NOT BETWEEN`, `ON LAST`, and `ON NEXT`. To try it out, click the filter icon next to the Date column in the left side menu, or click the date filter below the Answer or Liveboard title.
+
For more information, see
ifndef::pendo-links[]
xref:date-filter.adoc[Date filters for Answers and Liveboards].

Webhooks for KPI monitor alerts [.badge.badge-beta-relnotes]#Beta#:: You can create webhooks to initiate workflows in third-party applications based on KPI changes, or send KPI alert notifications to custom channels. For example, if you are monitoring a "current inventory" KPI for an inventory management use case, you can build a workflow to trigger an order placement in a third-party app when your current inventory drops below a particular threshold value. Webhooks for Monitor is in beta and off by default. To enable it, contact {support-url}.

Mobile enhancements:: We made the following enhancements to ThoughtSpot Mobile:

* We extended the length of mobile sessions on ThoughtSpot Cloud. If a user visits the mobile app at least once every two weeks, they will no longer be logged out.

* We introduced a Watchlist tab on Mobile to make it easier for users to follow important metrics.

* We simplified the log in process for the ThoughtSpot mobile app. You can now enter your company email to receive an email with a magic link login, rather than entering the server URL.


[#9-5-0-cl-data-engineer]
=== For the Data Engineer

SingleStore connection [.badge.badge-early-access-relnotes]#Early Access#:: You can now create connections from ThoughtSpot to SingleStore.
For details, see xref:connections-singlestore.adoc[Connect to SingleStore].


Redshift OAuth with Azure AD IDP:: Redshift now supports external OAuth through Microsoft Azure AD. See xref:connections-redshift-azure-ad-oauth.adoc[Configure Azure AD external OAuth for a Redshift connection].

[#9-5-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

[#9-5-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
