The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-4-0-cl-first,For the First User>>
* <<9-4-0-cl-analyst,For the Analyst>>
* <<9-4-0-cl-business-user,For the Business User>>
* <<9-4-0-cl-data-engineer,For the Data Engineer>>
* <<9-4-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-4-0-cl-developer,For the Developer>>

[#9-4-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-4-0-cl-analyst]
=== For the Analyst

Verified Liveboards:: Admin-assigned verifiers can now mark Liveboards as verified. Users can now request these verifiers to review their Liveboards, and verify if the information displayed is trusted content. Verified Liveboards carry a tag that signifies that they have been audited for correctness. For more information, see xref:liveboard-verify.adoc[Verified Liveboards].


[#9-4-0-cl-business-user]
=== For the Business User

Web notifications:: Users can now receive in-app notifications when items are shared with them, or when other users request access to an Answer or Liveboard. To view these notifications, simply click on the user profile icon. For more information, see xref:web-notifications.adoc[Web notifications].

AI Answer improvements::
We made the following changes to the AI Answer feature:

* Redesigned search results page. Filtering facets are now in the left panel.
* AI Answer is now interactive.
* Title and descriptions are now pre-populated when you save an AI Answer.

[#9-4-0-cl-data-engineer]
=== For the Data Engineer


Join creation for views:: The new join creation UI for views is now GA and on by default. We standardized the method of creating joins for all data objects in ThoughtSpot. When creating a join from a view, users are now directed to a *Create join* page where they can choose a connection, name the join, and map the source and destination columns.

[#9-4-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

New London cloud region:: ThoughtSpot Cloud is now available in London when you connect using AWS. See xref:ts-cloud-requirements-support.adoc[ThoughtSpot Cloud requirements and support].

[#9-4-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
