The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-4-0-cl-first,For the First User>>
* <<9-4-0-cl-analyst,For the Analyst>>
* <<9-4-0-cl-business-user,For the Business User>>
* <<9-4-0-cl-data-engineer,For the Data Engineer>>
* <<9-4-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-4-0-cl-developer,For the Developer>>

[#9-4-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-4-0-cl-analyst]
=== For the Analyst

Verified Liveboards:: Admin-assigned verifiers can now mark Liveboards as verified. Users can now request these verifiers to review their Liveboards, and verify if the information displayed is trusted content. Verified Liveboards carry a tag that signifies that they have been audited for correctness. For more information, see xref:liveboard-verify.adoc[Verified Liveboards].


[#9-4-0-cl-business-user]
=== For the Business User

[#9-4-0-cl-data-engineer]
=== For the Data Engineer


[#9-4-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

New London cloud region:: ThoughtSpot Cloud is now available in London when you connect using AWS. See xref:ts-cloud-requirements-support.adoc[ThoughtSpot Cloud requirements and support].

[#9-4-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
