The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-4-0-cl-first,For the First User>>
* <<9-4-0-cl-analyst,For the Analyst>>
* <<9-4-0-cl-business-user,For the Business User>>
* <<9-4-0-cl-data-engineer,For the Data Engineer>>
* <<9-4-0-cl-it-ops-engineer,For the IT Ops Engineer>>
* <<9-4-0-cl-developer,For the Developer>>

[#9-4-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-4-0-cl-analyst]
=== For the Analyst

Verified Liveboards:: Admin-assigned verifiers can now mark Liveboards as verified. Users can now request these verifiers to review their Liveboards, and verify if the information displayed is trusted content. Verified Liveboards carry a tag that signifies that they have been audited for correctness. For more information, see xref:liveboard-verify.adoc[Verified Liveboards].

Indexing Queries Liveboard:: We introduced a Liveboard to answer the following questions: +

* How many indexing queries are made?
* What queries are failing and why?
* How long are the indexing queries taking?
* Which connections have the most failures so that the admin can easily identify them?
+
Admin users can access the Indexing Queries Liveboard from the admin tab, and use the results to improve indexing queries performance. For more information, see xref:indexing-queries-liveboard.adoc[Indexing Queries Liveboard].



Geomap chart enhancements:: ThoughtSpot now supports the following enhancements for geomap visualizations:

* We now provide geomap data for all countries. For a full list, see link:https://wiki.openstreetmap.org/wiki/List_of_territory_based_projects[Openstreetmap supported countries].
* We now support visualizations comparing subdivisions of multiple countries in a single visualization. For example, if a selected column contains data from cities in the United States and Mexico, all data would be displayed on a single visualization.
* We now support multiple levels of subdivisions within a country, rather than just city and zip code.
* Zip code data is now visualized as an area within a region, rather than a point on a map.

[#9-4-0-cl-business-user]
=== For the Business User

Web notifications:: Users can now receive in-app notifications when items are shared with them, or when other users request access to an Answer or Liveboard. To view these notifications, simply click on the user profile icon. For more information, see xref:web-notifications.adoc[Web notifications].

AI Answer improvements::
We made the following changes to the AI Answer feature:

* Redesigned search results page. Filtering facets are now in the left panel.
* AI Answer is now interactive.
* Title and descriptions are now pre-populated when you save an AI Answer.

[#9-4-0-cl-data-engineer]
=== For the Data Engineer




[#9-4-0-cl-it-ops-engineer]
=== For the IT/Ops Engineer

New London cloud region:: ThoughtSpot Cloud is now available in London when you connect using AWS. See xref:ts-cloud-requirements-support.adoc[ThoughtSpot Cloud requirements and support].

[#9-4-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
