The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-11-0-cl-first,For the First User>>
* <<9-11-0-cl-analyst,For the Analyst>>
* <<9-11-0-cl-business-user,For the Business User>>
* <<9-11-0-cl-data-engineer,For the Data Engineer>>
* <<9-11-0-cl-developer,For the Developer>>

[#9-11-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-11-0-cl-analyst]
=== For the Analyst

// Naomi -- scal-177005
Advanced conditional formatting [.badge.badge-early-access-relnotes]#Early Access#::
Rather than simply using conditional formatting comparing a column's measures to a single value (for example, `sales > 10000`), you can now use conditional formatting to compare a column's measures to another column or to a parameter. For example, if you search for `sales this year` versus `sales last year`, you can highlight where sales this year were less than last year. You can set multiple conditional formatting rules to a single table.
For more information, see xref:search-conditional-formatting.adoc#advanced-conditional-formatting[Advanced conditional formatting].


// Naomi -- scal-174127
ThoughtSpot Sync for Google BigQuery::
ThoughtSpot Sync for Google BigQuery is now on by default and available to all users. Using ThoughtSpot Sync, you can now sync data directly from an Answer or a custom SQL view, to your Google BigQuery cloud data warehouse.
For more information, see xref:sync-gbq.adoc[Sync to Google BigQuery].




[#9-11-0-cl-business-user]
=== For the Business User

Keywords "of", "percentage of":: To enable business users to answer questions related to mix, contribution, share of, percentage, and total ratios, we added the keywords “of” and “percentage of”. These keywords help answer questions such as “What is the share of a certain store’s sales as a percentage of the regional whole?” Previously, searches such as these required the use of a group aggregate formula, which presented a barrier to users. +
For more information, see
xref:formulas-keywords.adoc[Keywords: Of and Percentage of].



[#9-11-0-cl-data-engineer]
=== For the Data Engineer


[#9-11-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
