The latest release of ThoughtSpot Cloud contains several new and enhanced features.

* <<9-11-0-cl-first,For the First User>>
* <<9-11-0-cl-analyst,For the Analyst>>
* <<9-11-0-cl-business-user,For the Business User>>
* <<9-11-0-cl-data-engineer,For the Data Engineer>>
* <<9-11-0-cl-developer,For the Developer>>

[#9-11-0-cl-first]
=== For the First User

Getting started with ThoughtSpot Cloud::
The first user on the account has to complete a series of steps before other people can start using ThoughtSpot with your organization's data.
For these instructions, see xref:ts-cloud-getting-started.adoc[Getting Started with ThoughtSpot Cloud].

[#9-11-0-cl-analyst]
=== For the Analyst


// Naomi -- scal-174127
ThoughtSpot Sync for Google BigQuery::
ThoughtSpot Sync for Google BigQuery is now on by default and available to all users. Using ThoughtSpot Sync, you can now sync data directly from an Answer or a custom SQL view, to your Google BigQuery cloud data warehouse.
For more information, see xref:sync-gbq.adoc[Sync to Google BigQuery].




[#9-11-0-cl-business-user]
=== For the Business User




[#9-11-0-cl-data-engineer]
=== For the Data Engineer


[#9-11-0-cl-developer]
=== For the Developer

ThoughtSpot Everywhere:: For information about the new features and enhancements introduced in this release, refer to https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
