ifndef::pendo-links[]
July 2024 [label label-dep]#10.0.0.cl#
endif::[]
ifdef::pendo-links[]
[month-year-whats-new]#July 2024#
[label label-dep-whats-new]#10.0.0.cl#
endif::[]

ifndef::free-trial-feature[]
NOTE: Features marked as [.badge.badge-update-note]#Beta# are off by default. To enable them, contact {support-url}.
endif::free-trial-feature[]

[#primary-10-0-0-cl]

// Business User


// Analyst

ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-0-0-cl-conditional]
[discrete]
=== Advanced conditional formatting [.badge.badge-early-access]#Early Access#
endif::[]
ifdef::pendo-links[]
[#10-0-0-cl-conditional]
[discrete]
=== Advanced conditional formatting [.badge.badge-early-access-whats-new]#Early Access#
endif::[]

// Naomi -- scal-177005. documentation JIRA scal-201639 (approved).
// PM: Manan

In addition to using conditional formatting to visually highlight a threshold in a measure (for example, `sales > 10000`), you can now use conditional formatting to compare a column's measures to another column or to a parameter. For example, if you search for `sales this year` compared to `sales last year`, you can highlight where sales this year were less than last year. You can set multiple conditional formatting rules to a single table. To enable this feature, contact your administrator.

For more information, see
ifndef::pendo-links[]
xref:search-conditional-formatting.adoc#advanced-conditional-formatting[Advanced conditional formatting].
endif::[]
ifdef::pendo-links[]
xref:search-conditional-formatting.adoc#advanced-conditional-formatting[Advanced conditional formatting,window=_blank].
endif::[]

video::adv-conditional-comparison.mp4[Advanced conditional formatting comparing sales this year to sales last year]
endif::free-trial-feature[]




ifndef::free-trial-feature[]
ifndef::pendo-links[]
[#10-0-0-cl-measures]
[discrete]
=== Blend axes for multiple measures in pivot tables  [.badge.badge-beta]#Beta#
endif::[]
ifdef::pendo-links[]
[#10-0-0-cl-measures]
[discrete]
=== Blend axes for multiple measures in pivot tables [.badge.badge-beta-whats-new]#Beta#
endif::[]

ThoughtSpot now supports blending axes for multiple measures in pivot tables. You can now move measures, and position them where you want in rows and columns.
// Mary. SCAL-181678. docs JIRA: SCAL-211771
// add gif or image. beta in 10.0.0.cl
// PM: Manan
//The feature will remain disabled and behind a flag. Only specific customers would enable it using tscli commads. Beta for 10.0.cl.

endif::free-trial-feature[]


'''
[#secondary-10-0-0-cl]
[discrete]
=== _Other features and enhancements_

// Data Engineer


// IT/ Ops Engineer


[#10-0-0-cl-orgs]
[discrete]
=== Org deletion - Default enablement
You can now delete an Org without first manually deleting the data objects, connections, groups, and users within the Org. Contact {support-url} to enable Org deletion.
// Mary. SCAL-179795. docs JIRA: SCAL-201819
// PM: Kiran, Vijay, Aashica
// Waiting for confirmation from Aashica as to whether or not they will actually need to contact support to enable this since the title was changed to "Default enablement".

ifndef::free-trial-feature[]
[discrete]
=== For the Developer

For new features and enhancements introduced in this release of ThoughtSpot Embedded, see https://developers.thoughtspot.com/docs/?pageid=whats-new[ThoughtSpot Developer Documentation^].
endif::[]